### ISSUE TITLE
Question about LinearRegressionL1L2TV

### ISSUE THREAD

**Issue by fighting41love** [neurospin/pylearn-parsimony#14]
The following two parameters of LinearRegressionL1L2TV:
**A : Numpy or (usually) scipy.sparse array. The linear operator for the smoothed total variation Nesterov function. A must be given.**
**mu : Non-negative float. The regularization constant for the smoothing.**

I don't know why it works. How does it work?
Could anyone show some papers about the two parameters?

Thanks!

**Comment by tomlof** [comment]
The details of these parameters are given in this paper: https://arxiv.org/abs/1605.09658

The short version is that the matrix A encodes the structure of the penalty, i.e., it describes the complex relationships between the variables. In the TV case, the A matrix encodes the spatial derivatives in each dimension of your data, usually this is encoded as a forward difference, in which case the rows of A contains just a single 1 and a single -1, encoding the difference between the corresponding variables. This matrix can be generated by the functions `linear_operator_from_*` in `parsimony.functions.nesterov.tv`. You can also look at the unit tests or the examples to see how to use these parameters.

The mu is a positive float that controls the smoothing of the complex structured penalty (TV in this case). A small value of mu means that the function is very close to the original function being smoothed, but also that the minimisation algorithm will require many iterations to converge. A large value means that the original function is heavily smoothed, but also that it will require few iterations to converge to the minimum. There is a trade-off here between how close the smoothed approximation is to the original function and how fast we want to converge to the optimum. Further, if you use the CONESTA algorithm, for instance, you do not have to supply the mu, since the algorithm takes care of it.

**Comment by fighting41love** [comment]
The paper is interesting! I'd like to cite it in my paper.
Thanks for your detailed response !
I really appreciate that.
Thanks!
