### ISSUE TITLE
helper to generate linear operator refactoring

### ISSUE THREAD

**Issue by duchesnay** [neurospin/pylearn-parsimony#9]
1) Harmonize linear operator construction helper: some helper return A, some return A, n_compact. Proposition all helper return **only** A

2) linear operator is actually a simple list. We would like to:
-  store information like the Lipschitz constant (that could be computed only once and reused) and eventually the n_compacts
- Provide serialization to disk. This would also also a lot of computation time

I propose to create an object LinearOperator which **is a list** (inherits from a list) this way it will not impact the code. I propose to add, at least, 3 methods:
- L() return the Lipschitz constant, could be None
- load(filename): npz format not pickle !
- save(filename)

Question should we move from helper to statics constructors ?

**Comment by tomlof** [comment]
I totally agree with 1.

Point 2 seems like a good idea! Two comments:

  * It is the Lipschitz constant of the gradient of the function that uses the linear operator that is considered. For A this means the largest squared singular value of A (largest eigenvalue of A'*A). This eigenvalue is then used in the computation of the Lipschitz constants, but this use is "unknown" from the point-of-view of the A matrix. Therefore, instead of L(), the function should be called sigma_max() or lambda_max(), or something like that.

  * I think this class that inherits from list should be put in the existing module parsimony.utils.linalgs.

**Comment by duchesnay** [comment]
Totally agree with both comments, I am working on it

**Comment by duchesnay** [comment]
Point 1: harmonization is done commit: 0aebc160d5978d0d6637cef2a42278281beb16f6
Now working on point 2

**Comment by tomlof** [comment]
Perfect!

**Comment by duchesnay** [comment]
Done
